### PR TITLE
feat(334): validation support in TextInput

### PR DESCRIPTION
**Pull request by techeclecticdesign**
Instead of using setError I used the built in validation support via register by adding an optional field to TextInput.
I wanted to get opinion on this, I thought it would be more versatile.  I would be happy to set this up with setError instead if that is your preference.
I like that it live auto-updates as you type instead of waiting for submit.

### CODE REVIEW

**Review by PThorpe92 — APPROVED** [review]
Looks good to me :+1: 

thanks for this

**Comment by jtucholski** [comment]
Hey @techeclecticdesign

> I like that it live auto-updates as you type instead of waiting for submit.

I'm seeing the new error message, but I'm not seeing any validation as I type. I see it when I press Submit. Is there any chance I'm missing something?

https://github.com/user-attachments/assets/77857c03-0b8d-4178-a885-daee79cbba3f

**Comment by techeclecticdesign** [comment]
Hi @jtucholski,
Playing with it a little I am seeing the live updating only happens after the first bad submission.
It seems this is the default behavior with react-hook-forms.

**Comment by calisio** [comment]
You might be able to use `watch` for real time validation? Not 100% sure but from briefly looking at it it might provide a solution. https://react-hook-form.com/docs/useform/watch

**Comment by PThorpe92** [comment]
Hey so I see that this was meant to take care of #334

I previously thought it was only in the scope of adding the generic form validation for the text input.

If it is going to clear up that ticket, can we add validation on the backend? I have been meaning to add this library to handle all of our forms. https://github.com/go-playground/validator

**Comment by techeclecticdesign** [comment]
Sorry for the delay in reply, I didn't have access to a computer for a few days.
So to clarify, instead of the built-in frontend validation with react-hook-forms, I should handle validation on the backend after the form has been submitted with the validator library.  Sound good?

**Pull request closed without merging**
