### PR TITLE
PageNav dropdown updates #412

### LINKED ISSUE #412: PageNav dropdown updates
`PageNav.tsx` needs some small updates to styling. All three should be completed to finish this ticket.

1. For admin, there are still links to pages in the page nav dropdown. These links should be removed except the toggle and logout buttons to reduce redundancy and confusion. Below is what the dropdown currently looks like.

2. When a user has a long name, the dropdown left aligns with the name. This should be changed to right align to look better.

3. Currently, we use svg tags for the sun and moon on the toggle button. These should be replaced with heroicons like it is used in the rest of the codebase. I believe they should both be outline to match what they currently look like. The height and width would be `w-5 h-5` to be the same size as it is now. The code that should be replaced is copied below:

```jsx
<label className="flex cursor-pointer gap-2">
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="20"
    height="20"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <circle cx="12" cy="12" r="5" />
    <path d="M12 1v2M12 21v2M4.2 4.2l1.4 1.4M18.4 18.4l1.4 1.4M1 12h2M21 12h2M4.2 19.8l1.4-1.4M18.4 5.6l1.4-1.4" />
  </svg>
  <ThemeToggle />
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="20"
    height="20"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path>
  </svg>
</label>;
```

### PR DESCRIPTION
**Pull request by corypride**
## Description of the change
heroIcon refactor and link removal

- **Related issues**: Link to related issue(s) this PR addresses, if any (use phrases like "fixes #1234" or "closes #1234").
Closes #412 
## Screenshot(s)
image

## Additional context

### CODE REVIEW

**Comment by calisio** [comment]
Ya, I wasn't sure how feasible changing that would be, mainly because its daisyUI and those components are usually a pain to change. Let me take a look and see if I can figure it out and I'll get back to you.

**Comment by calisio** [comment]
Ok- I found a solution! If you go onto the daisyUI docs, there is a class/component called [dropdown](https://daisyui.com/components/dropdown/). It provides the functionality that we would like, and also allows for [dropdown-end](https://daisyui.com/components/dropdown/#dropdown--aligns-to-end), which will align it to the right hand side. If you add `dropdown dropdown-end` to the `<details>` tag, and then add `dropdown-content` to the `<ul>` tag, I think that should solve the issue. I also noticed that it uses `bg-base-300`, could you change it to `bg-grey-2`?

**Comment by corypride** [comment]
@calisio that did not seem to have any affect on the spacing.....

**Review by calisio — APPROVED** [review]
Looks great, thanks Cory!

**Pull request merged**
