### PR TITLE
fix title: Laravel -> UnlockEdv2

### PR DESCRIPTION
**Pull request by techeclecticdesign**

### CODE REVIEW

**Review by PThorpe92 — APPROVED** [review]

**Comment by PThorpe92** [comment]
Hey man, thanks for the PR! Looks good :+1: 

Could you --amend your commit to meet conventional commit standards? We use it for our changelog, and the CI check is pretty strict about it. 

https://www.conventionalcommits.org/en/v1.0.0/#summary

`fix: change title from laravel to product name` 

or something along those lines, and we can get it merged :rocket:

**Comment by techeclecticdesign** [comment]
Hi Preston,
Please bear with me as I get a work flow going.  I adapt quick, but I might
have a couple bumps on the road at first.
I didn't know you guys had this all open source, so of course I want to
participate.
Regards,
-chris

**Comment by coledykstra** [comment]
Hi Chris,
I messed up my first commit msg too. Then I made this:
[https://coledykstra.github.io/]

**Comment by PThorpe92** [comment]
Hey Chris, just a quick general tip:

When contributing to projects you generally will want to `git commit --amend` and then force push any changes remotely after you make after the initial PR. If you ever have to change a commit message, or there is a small update you want to add to the PR, this allows you to do alter your PR's commits without merge/revert commits. Larger projects tend to maintain changelogs based on the git history and generally try to keep it as clean and concise as possible. Like I said this is just general advice/good practice, and will apply to most projects you contribute to.

Check out that commit message generator that Cole linked, and if you don't mind (I can do it for you if you aren't sure how) rebasing your changes to 1 commit (that complies with the conventional commit standard), so the CI will pass. :+1:

**Comment by techeclecticdesign** [comment]
Thank you Preston,
I noticed after the fact that the reverts had polluted the commit history.
I didn't know I can rebase changes and I will research how to do this.
Until I get the hang of things, I will be a few degrees more cautious
moving forward.  This will be my first time using git collaboratively, and
it has been a very long time since I was using subversion.
To be clear, I should make 2 commits, one for title change and one for
faded chevrons when inactive? or should I combine these into a single
commit?
Regards,
-chris

**Pull request closed without merging**
